export const strings = {
  loginButtonTitle: 'Login here',
  signUpButtonTitle: 'Sign up',
  loginSignUpScreenText: 'Already have an account?',
  remember: 'Remember me?',
  forgotPassword: 'Forgot password',
  singIn: 'Sign In',
  signUp: 'Sign up',
  email: 'Email',
  password: 'Password',
  mobile: 'Mobile',
  next: 'Next',
  confirm: 'Confirm',
  send: 'Send',
  validate: 'validate',
  new: 'new',
};
